=== Zerattel/HayatBattleshipCalculator/schemas/modules.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Module",
  "type": "object",
  "required": ["main", "activation", "modificators"],
  "properties": {
    "main": {
      "type": "object",
      "required": ["name", "type", "category", "size", "position"],
      "properties": {
        "name": { "type": "string" },
        "type": { "type": "string" },
        "category": { "type": "string" },

        "class": { "type": "string" },

        "size": { "type": "number" },
        "position": {
          "type": "string",
          "enum": ["internal", "external"]
        },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        }
      }
    },

    "activation": {
      "type": "string",
      "enum": ["passive", "active", "overload"]
    },

    "initFunctions": { "type": "string" },

    "interference": { "type": "number" },

    "cycle": { "type": "number" },
    "reload": { "type": "number" },

    "launcher": { 
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "heading": { "type": "number" },
            "vector": {
              "type": "array",
              "items": { "type": "number" },
              "minItems": 2,
              "maxItems": 2
            },
            "subgridRotation": { "type": "number" },
            "distanceOffset": { "type": "number" },
            "backupDistance": { "type": "number" },
            "recovery": {
              "type": "object",
              "properties": {
                "fuel": { "type": "number" },
                "temperature": { "type": "number" },
                "hp": {
                  "type": "object",
                  "properties": {
                    "hull": { "type": "number" },
                    "armor": { "type": "number" },
                    "barrier": { "type": "number" }
                  }
                }
              }
            }
          }
        },
        {
          "type": "object",
          "required": ["instances"],
          "properties": {
            "heading": { "type": "number" },
            "instances": {
              "type": "array",
              "items": {
                "type": "object",
                "required": ["vector", "headingOffset", "distanceOffset", "subgrid"],
                "properties": {
                  "vector": {
                    "type": "array",
                    "items": { "type": "number" },
                    "minItems": 2,
                    "maxItems": 2
                  },
                  "headingOffset": { "type": "number" },
                  "distanceOffset": { "type": "number" },
                  "subgridRotation": { "type": "number" },

                  "fire": {
                    "type": "object",
                    "required": ["type", "delay"],
                    "properties": {
                      "type": { "type": "string" },
                      "delay": {
                        "oneOf": [
                          { "type": "number" },
                          {
                            "type": "array",
                            "items": { "type": "number" }
                          }
                        ]
                      }
                    }
                  },

                  "subgrid": {
                    "type": "object",
                    "required": ["class", "dataRef"],
                    "properties": {
                      "class": { "type": "string" },
                      "dataRef": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    },

    "additionalInfo": {
      "type": "object"
    },

    "modificators": {
      "type": "object",
      "required": ["offline", "online", "active", "overload"],
      "properties": {
        "offline": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "online": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "active": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "overload": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        }
      }
    },

    "external": {
      "type": "object",
      "patternProperties": {
        "^.*$": { 
          "type": "string",
          "pattern": "^([\\w-_]+(\\/|.json))+$"
        }
      }
    }
  },

  "definitions": {
    "modRecord": {
      "type": "object",
      "required": ["target", "characteristic", "modificationType", "modificator"],
      "properties": {
        "target": {
          "type": "string",
          "enum": ["this", "target", "area"]
        },
        "characteristic": { "type": "string" },

        "modificationType": {
          "type": "string",
          "enum": ["number", "percent"]
        },

        "modificator": {
          "oneOf": [
            { "type": "number" },
            { "type": "string" }
          ]
        },

        "isAffectedByInterference": { "type": "boolean" }
      }
    }
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/launchers/test/railgun-test.json
{
  "main": {
    "name": "Рельсотрон",
    "type": "Стартовые площадки",
    "category": "Высокомощные ускорители",
    "class": "SubgridLauncherModule",

    "size": 1,
    "position": "external",
    "tags": ["catapult", "subgrid", "railgun"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 3,

  "interference": 0,

  "launcher": {
    "heading": 0,
    "instances": [
      {
        "vector": [0, 1600],

        "headingOffset": 0,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "single",
          "delay": 0
        },

        "subgrid": {
          "class": "ShellSubgridObject",
          "dataRef": "[Test] Railgun Shell (10m)"
        }
      }
    ]
  },

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -5,
        "isAffectedByInterference": false
      }
    ],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -9,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/shiptype-profile/sss-lurker-mkII-stp.json
{
  "main": {
    "name": "Проф. Особенность типа «Lurker MkII»",
    "type": "Проф. Особенность типа",
    "category": "Проф. Особенность Фрегата",

    "size": 0,
    "position": "internal",
    "tags": ["stp"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
        {
        "target": "this",
        "characteristic": "constant.maneuverability",
        "modificationType": "number",
        "modificator": 2,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.modulemodifier.engineering.thermodynamic.signature_penalty_modifier",
        "modificationType": "number",
        "modificator": -0.5,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/launchers/test/mine-layer-test.json
{
  "main": {
    "name": "Миноукладчик S (электромагнитный)",
    "type": "Стартовые площадки",
    "category": "Катапульты",
    "class": "SubgridLauncherModule",

    "size": 1,
    "position": "external",
    "tags": ["catapult", "subgrid", "minelayer"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 4,

  "interference": 0,

  "launcher": {
    "heading": 0,
    "instances": [
      {
        "vector": [0, 200],

        "headingOffset": -160,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "rapid",
          "delay": [0, 2, 4]
        },

        "subgrid": {
          "class": "MineSubgridObject",
          "dataRef": "[Test] Мина S"
        }
      },
      {
        "vector": [0, 200],

        "headingOffset": -180,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "rapid",
          "delay": [0, 2, 4]
        },

        "subgrid": {
          "class": "MineSubgridObject",
          "dataRef": "[Test] Мина S"
        }
      },
      {
        "vector": [0, 200],

        "headingOffset": 160,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "rapid",
          "delay": [0, 2, 4]
        },

        "subgrid": {
          "class": "MineSubgridObject",
          "dataRef": "[Test] Мина S"
        }
      }
    ]
  },

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -5,
        "isAffectedByInterference": false
      }
    ],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -15,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/pilot-drug-effects/kary.json
{
  "main": {
    "name": "D3 «Кари»",
    "type": "Наркотик",
    "category": "Доза-3",

    "size": 0,
    "position": "internal",
    "tags": ["psychoserocin"]
  },
  "activation": "passive",
  "interference": -1,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.modulemodifier.engineering.thermodynamic.radiation_modifier",
        "modificationType": "number",
        "modificator": 0.075,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.resistance.EW",
        "modificationType": "number",
        "modificator": -10,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}
