=== Zerattel/HayatBattleshipCalculator/schemas/modules.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Module",
  "type": "object",
  "required": ["main", "activation", "modificators"],
  "properties": {
    "main": {
      "type": "object",
      "required": ["name", "type", "category", "size", "position"],
      "properties": {
        "name": { "type": "string" },
        "type": { "type": "string" },
        "category": { "type": "string" },

        "class": { "type": "string" },

        "size": { "type": "number" },
        "position": {
          "type": "string",
          "enum": ["internal", "external"]
        },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        }
      }
    },

    "activation": {
      "type": "string",
      "enum": ["passive", "active", "overload"]
    },

    "initFunctions": { "type": "string" },

    "interference": { "type": "number" },

    "cycle": { "type": "number" },
    "reload": { "type": "number" },

    "launcher": { 
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "heading": { "type": "number" },
            "vector": {
              "type": "array",
              "items": { "type": "number" },
              "minItems": 2,
              "maxItems": 2
            },
            "subgridRotation": { "type": "number" },
            "distanceOffset": { "type": "number" },
            "backupDistance": { "type": "number" },
            "recovery": {
              "type": "object",
              "properties": {
                "fuel": { "type": "number" },
                "temperature": { "type": "number" },
                "hp": {
                  "type": "object",
                  "properties": {
                    "hull": { "type": "number" },
                    "armor": { "type": "number" },
                    "barrier": { "type": "number" }
                  }
                }
              }
            }
          }
        },
        {
          "type": "object",
          "required": ["instances"],
          "properties": {
            "heading": { "type": "number" },
            "instances": {
              "type": "array",
              "items": {
                "type": "object",
                "required": ["vector", "headingOffset", "distanceOffset", "subgrid"],
                "properties": {
                  "vector": {
                    "type": "array",
                    "items": { "type": "number" },
                    "minItems": 2,
                    "maxItems": 2
                  },
                  "headingOffset": { "type": "number" },
                  "distanceOffset": { "type": "number" },
                  "subgridRotation": { "type": "number" },

                  "fire": {
                    "type": "object",
                    "required": ["type", "delay"],
                    "properties": {
                      "type": { "type": "string" },
                      "delay": {
                        "oneOf": [
                          { "type": "number" },
                          {
                            "type": "array",
                            "items": { "type": "number" }
                          }
                        ]
                      }
                    }
                  },

                  "subgrid": {
                    "type": "object",
                    "required": ["class", "dataRef"],
                    "properties": {
                      "class": { "type": "string" },
                      "dataRef": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    },

    "additionalInfo": {
      "type": "object"
    },

    "modificators": {
      "type": "object",
      "required": ["offline", "online", "active", "overload"],
      "properties": {
        "offline": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "online": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "active": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "overload": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        }
      }
    },

    "external": {
      "type": "object",
      "patternProperties": {
        "^.*$": { 
          "type": "string",
          "pattern": "^([\\w-_]+(\\/|.json))+$"
        }
      }
    }
  },

  "definitions": {
    "modRecord": {
      "type": "object",
      "required": ["target", "characteristic", "modificationType", "modificator"],
      "properties": {
        "target": {
          "type": "string",
          "enum": ["this", "target", "area"]
        },
        "characteristic": { "type": "string" },

        "modificationType": {
          "type": "string",
          "enum": ["number", "percent"]
        },

        "modificator": {
          "oneOf": [
            { "type": "number" },
            { "type": "string" }
          ]
        },

        "isAffectedByInterference": { "type": "boolean" }
      }
    }
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/weapons/beacon.json
{
  "main": {
    "name": "ИК Лазер «Светило»",
    "type": "Орудия",
    "category": "Лазеры",

    "size": 3,
    "position": "external",
    "tags": ["gun", "offencive", "laser"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 0,

  "interference": 0,

  "additionalInfo": {
    "baseDamage": 66,
    "targetHeating": 0.06,
    "effectiveRange": 27000,
    "maxRange": 40500,
    "tracking": 8
  },

  "initFunctions": "<[LaserAttack]>",

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.06,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -76,
        "isAffectedByInterference": false
      },
      {
        "target": "target",
        "characteristic": "dynamic.recived_damage.thermal",
        "modificationType": "number",
        "modificator": "module.functionsSharedData.perStep.damage",
        "isAffectedByInterference": false
      },
      {
        "target": "target",
        "characteristic": "dynamic.temperature",
        "modificationType": "number",
        "modificator": "module.functionsSharedData.perStep.heating",
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/weapons/gecko.json
{
  "main": {
    "name": "Артиллерия «Гекон» S",
    "type": "Орудия",
    "category": "Баллистика",

    "size": 1,
    "position": "external",
    "tags": ["gun", "offencive", "ballistic"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 3,

  "interference": 0,

  "additionalInfo": {
    "baseDamage": 60,
    "targetHeating": 0,
    "effectiveRange": 30000,
    "penaltyStep": 5000,
    "penalty": 1,
    "tracking": 4
  },

  "initFunctions": "<[BallisticAttack]>",

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.08,
        "isAffectedByInterference": false
      },
      {
        "target": "target",
        "characteristic": "dynamic.recived_damage.kinetic",
        "modificationType": "number",
        "modificator": "module.functionsSharedData.perStep.damage",
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/launchers/test/electromagnetic-catapult-test.json
{
  "main": {
    "name": "Электромагнитная торпедная катапульта",
    "type": "Стартовые площадки",
    "category": "Катапульты",
    "class": "SubgridLauncherModule",

    "size": 1,
    "position": "external",
    "tags": ["catapult", "subgrid"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 2,

  "interference": 0,

  "launcher": {
    "heading": 0,
    "instances": [
      {
        "vector": [0, 50],

        "headingOffset": 70,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "single",
          "delay": 0
        },

        "subgrid": {
          "class": "SelfguidedSubgridObject",
          "dataRef": "[Test] Torpedo T"
        }
      },
      {
        "vector": [0, 50],

        "headingOffset": -70,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "single",
          "delay": 0
        },

        "subgrid": {
          "class": "SelfguidedSubgridObject",
          "dataRef": "[Test] Torpedo T"
        }
      }
    ]
  },

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -5,
        "isAffectedByInterference": false
      }
    ],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -15,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/shiptype-profile/zd-moth-stp.json
{
  "main": {
    "name": "Проф. Особенность типа «Мотылёк»",
    "type": "Проф. Особенность типа",
    "category": "Проф. Особенность Эсминца",

    "size": 0,
    "position": "internal",
    "tags": ["stp"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.modulemodifier.offence.launcher.fuel_modifier",
        "modificationType": "number",
        "modificator": -0.25,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.modulemodifier.offence.launcher.acceleration_modifier",
        "modificationType": "number",
        "modificator": 0.5,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.modulemodifier.offence.launcher.explosion_signature_modifier",
        "modificationType": "number",
        "modificator": -0.175,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.modulemodifier.engineering.barrier.resonance.tendency",
        "modificationType": "number",
        "modificator": 0.15,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/launchers/test/rapid-fire-launcher.json
{
  "main": {
    "name": "Ракетный комплекс «Рой»",
    "type": "Стартовые площадки",
    "category": "Ракетные комлексы",
    "class": "SubgridLauncherModule",

    "size": 1,
    "position": "external",
    "tags": ["catapult", "subgrid"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 2,

  "interference": 0,

  "launcher": {
    "heading": 0,
    "instances": [
      {
        "vector": [0, 50],

        "headingOffset": 70,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "rapid",
          "delay": [0, 1, 2]
        },

        "subgrid": {
          "class": "SelfguidedSubgridObject",
          "dataRef": "[Test] Ракета типа \"Рой\""
        }
      },
      {
        "vector": [0, 50],

        "headingOffset": -70,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "rapid",
          "delay": [0, 1, 2]
        },

        "subgrid": {
          "class": "SelfguidedSubgridObject",
          "dataRef": "[Test] Ракета типа \"Рой\""
        }
      },
      {
        "vector": [0, 50],

        "headingOffset": 80,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "rapid",
          "delay": [0.5, 1.5]
        },

        "subgrid": {
          "class": "SelfguidedSubgridObject",
          "dataRef": "[Test] Ракета типа \"Рой\""
        }
      },
      {
        "vector": [0, 50],

        "headingOffset": -80,
        "distanceOffset": 0,
        "subgridRotation": 0,

        "fire": {
          "type": "rapid",
          "delay": [0.5, 1.5]
        },

        "subgrid": {
          "class": "SelfguidedSubgridObject",
          "dataRef": "[Test] Ракета типа \"Рой\""
        }
      }
    ]
  },

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -15,
        "isAffectedByInterference": false
      }
    ],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -40,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/hangars/test/hangar-test.json
{
  "main": {
    "name": "Ангар дрона «Миллер»",
    "type": "Ангары",
    "category": "Малые ангары",
    "class": "DroneLauncherModule",

    "size": 1,
    "position": "internal",
    "tags": []
  },
  "activation": "active",
  "interference": 0,

  "launcher": {
    "vector": [0, 50],
    "heading": 180,

    "subgridRotation": 0,
    "distanceOffset": 0,
    
    "backupDistance": 100,
    "recovery": {
      "fuel": 12,
      "hp": {
        "armor": 4,
        "hull": 10
      }
    }
  },

  "modificators": {
    "offline": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -2,
        "isAffectedByInterference": false
      }
    ],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -8,
        "isAffectedByInterference": false
      }
    ],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -15,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  },

  "external": {
    "battleship_template": "templates/miller-drone-test.json"
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/electromagnetic-catapult-test.json
{
  "main": {
    "name": "Электромагнитная торпедная катапульта",
    "type": "Стартовые площадки",
    "category": "Катапульты",
    "class": "SubgridLauncherModule",

    "size": 1,
    "position": "external",
    "tags": ["catapult", "subgrid"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 5,

  "interference": 0,

  "launcher": {
    "vector": [0, 120],
    "headingOffset": 0,
    "subgrid": {
      "class": "SubgridObject",
      "dataRef": "Torpedo T"
    }
  },

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -5,
        "isAffectedByInterference": false
      }
    ],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -15,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Zerattel/HayatBattleshipCalculator/modules/weapons/veles.json
{
    "main": {
    "name": "Энтр. Дезинтегр. «Велес»",
    "type": "Орудия",
    "category": "Предтеч",
    "size": 2,
    "position": "external",
    "tags": ["gun", "offencive", "entropic", "precursor"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 0,
  "interference": 0,
  "additionalInfo": {
    "baseDamage": 60,
    "targetHeating": 0.02,
    "effectiveRange": 15000,
    "maxRange": 22500,
    "tracking": 45,
    "perStepBonus": 0.06,
    "bonusCap": 2.0
  },
  "initFunctions": "<[EntropicDisintegrator]>",
  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.06,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -8,
        "isAffectedByInterference": false
      },
      {
        "target": "target",
        "characteristic": "dynamic.recived_damage.thermal",
        "modificationType": "number",
        "modificator": "module.functionsSharedData.perStep.damage",
        "isAffectedByInterference": false
      },
      {
        "target": "target",
        "characteristic": "dynamic.temperature",
        "modificationType": "number",
        "modificator": "module.functionsSharedData.perStep.heating",
        "isAffectedByInterference": false
      }
    ],
    "overload": []
    }
}
